### ISSUE TITLE
Utworzyć endpoint do połączenia się symulatora z backendem

### ISSUE THREAD

**Issue by ondreo** [pb-iot/backend#51]
Należy utworzyć endpoint, który by umożliwił symulatorowi okresowe wysyłanie danych na temat wszystkich szklarni i czujników. Ewentualnie, jeśli już istnieje taki endpoint, prosiłbym o wskazanie go.

Bez tego, nie będziemy w stanie zintegrować obu tych funkcjonalności, a czas dosyć nagli.

@pb-iot/backend

**Comment by sobek123** [comment]
Gdzie jest link do tego endpointu?

**Comment by patrycjarecko** [comment]
/graphql - pod to strzelacie mutacja z parametrami jako POST

**Comment by sobek123** [comment]
I ta mutacja ma byc zapisana jako string zwykly?

**Comment by patrycjarecko** [comment]
tak

**Comment by patrycjarecko** [comment]
https://docs.spring.io/spring-graphql/reference/client.html

**Comment by sobek123** [comment]
Mam dwa pytania: 
1. Czy dokładny link to: https://gm-api.wvffle.net/graphql?
2. Zaktualizowaliście swój kod, bo mi 500 leci przy POST?
3. 
![obraz](https://github.com/pb-iot/backend/assets/65244789/5507da1b-0faa-4cda-9e6a-d9a99a9fb796)

**Comment by wvffle** [comment]
> Czy dokładny link to: https://gm-api.wvffle.net/graphql?

Tak, ale powinniscie dodac env vara by moc to skonfigurowac.

> Zaktualizowaliście swój kod, bo mi 500 leci przy POST?

Najnowsze zmiany, ktore sa wrzucone to: d35d0405ac8a58cbc7793399af1b9ce1148c83d1

**Comment by sobek123** [comment]
@patrycjarecko Zaktualizowaliście swój kod, bo mi 500 leci przy POST?

**Comment by sobek123** [comment]
@wvffle env vara tzn.?

**Comment by patrycjarecko** [comment]
nie latwiej wam bedzie postawic sobie backend lokalnie? w readme jest instrukcja
nic nie zmienialismy w kodzie, blad ktory wyslaliscie nic mi nie mowi, moze sprobujcie obsluzyc 500 tak aby zwracalo wam konkretne info z czym jest problem

ewentualnie pokazcie kod, ktorym strzelacie z mutacja
